### ISSUE TITLE
Please provide EXACT installation instructions.

### ISSUE THREAD

**Issue by Khalian** [vhakulinen/neovim-intellij-complete#11]
Since this is not a part of the intelliJ plugins repository, an EXACT STEP BY STEP installation guide would be very very appreciated, along with pointers to usage.

**Comment by vhakulinen** [comment]
Download the plugin from releases page of this repo and install the plugin into the IDE. See here for how to install plugin from disk: https://www.jetbrains.com/help/idea/installing-a-plugin-from-the-disk.html?search=plugin
