### ISSUE TITLE
Add support for other languages

### ISSUE THREAD

**Issue by zhranklin** [vhakulinen/neovim-intellij-complete#4]
It seems that the completion shows up only when editing java files. But I want intellij's completion mainly for scala because it's really a complex language to provide a good auto-completion. It will be great if anything would be done for this!

**Comment by vhakulinen** [comment]
This is just from top of my head, but autocompletion for java files if defined in (here)[https://github.com/vhakulinen/neovim-intellij-complete-deoplete/blob/master/rplugin/python3/deoplete/sources/intellij.py]. If you define deoplete source for other languages, it should work (just change filetypes and input_patterns). Currently I dont have much time to work on this my self.

**Comment by zhranklin** [comment]
Thanks! I have tried to modify this file but I forgot to add a deoplete source😂

**Comment by zhranklin** [comment]
Thanks! But this doesn't work. I just wrote this:`self.filetypes = ['java', 'scala']` and didn't change the input_pattern because it's similar to java. When I'm editing java files, it works. But in scala files, it doesn't. Is there anything should be change in intellij side, e.g. I guess https://github.com/vhakulinen/neovim-intellij-complete/blob/master/neovim-intellij-complete.iml

**Comment by vhakulinen** [comment]
It is working for me but I had to `:set filetype=scala` in neovim because its not detecting the filetype automatically for some reason.
